name: Prettier Autoformat

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Prettier
        run: npm install --global prettier

      - name: Run Prettier
        run: |
          prettier . --write
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "style: auto-format with Prettier" || echo "Nothing to commit"
          git push
